main: io.github.gameplayerpl.EssentialsGP
name: EssentialsGP
version: 0.1
author: GamePlayer
description: Minecraft Java Plugin
api-version: 1.16
website: https://github.com/GamePlayer-PL/EssentialsGP
